In [1]:
import numpy as np

In [19]:
np.random.seed(42)
a = np.random.randint(2, 10, size=(3,1))
b = np.random.randint(2, 10, size=(7,1))
print(a)
print(b)

[[8]
 [5]
 [6]]
[[8]
 [4]
 [9]
 [6]
 [6]
 [8]
 [3]]


In [20]:
np.vstack((a,b))

array([[8],
       [5],
       [6],
       [8],
       [4],
       [9],
       [6],
       [6],
       [8],
       [3]])