In [12]:
import numpy as np
import pickle


In [16]:
def load_cifar_batch(file_path):
    with open(file_path, 'rb') as f:
        batch = pickle.load(f, encoding='bytes')
        data = batch[b'data']
        labels = batch[b'labels']
        # cifar-10 stores raw vector 3072 bytes. reshaping to 3 channel * 32 height * 32 width
        images = data.reshape(-1, 3, 32, 32).transpose(0, 2, 3, 1)
        return data, np.array(labels)


def load_cifar_10_dataset(file_directory):

    train_images = []
    train_labels = []
    for i in range(1, 6, 1):
        images, labels = load_cifar_batch(f"{file_directory}/data_batch_{i}")
        train_images.append(images)
        train_labels.append(labels)
    Xtrain = np.concatenate(train_images)
    Ytrain = np.concatenate(train_labels)

    Xtest, Ytest = load_cifar_batch(f"{file_directory}/test_batch")

    return Xtrain, Ytrain, Xtest, Ytest



Xtrain, ytrain, Xtest, ytest = load_cifar_10_dataset('/Users/subhojit/Downloads/cifar-10-batches-py')
Xtrain.shape, ytrain.shape, Xtest.shape, ytest.shape


((50000, 3072), (50000,), (10000, 3072), (10000,))

In [21]:
Xtest[10, :]

array([ 90,  90,  91, ..., 148, 146, 146], dtype=uint8)

In [22]:
np.abs(Xtrain - Xtest[10,:])

array([[225, 209, 215, ..., 248, 194, 182],
       [ 64,  36,  14, ..., 247, 252, 254],
       [165, 163, 162, ..., 191, 193, 194],
       ...,
       [201, 206, 207, ..., 185, 176, 160],
       [ 99,  96,  94, ...,  21,  25,  25],
       [139, 146, 143, ...,  25,  16,  15]], dtype=uint8)

In [27]:
a = np.random.randint(1, 10, size=(2,3))
b = np.random.randint(1, 10, size=(3,4))
c = np.dot(a, b)
c

array([[47, 76, 47, 64],
       [42, 59, 37, 53]])