In [19]:
import torch
import torch.nn.functional as F
import matplotlib.pyplot as plt
%matplotlib inline


In [20]:
# The paper where the idea came out well to have multiple layers of neurons
# https://www.jmlr.org/papers/volume3/bengio03a/bengio03a.pdf

words = open('names.txt', 'r').read().splitlines()
words[:5]

['emma', 'olivia', 'ava', 'isabella', 'sophia']

In [ ]:
list_chars = sorted(list(set(''.join(words))))
stoi = {}
itos = {}
idx = 1
for ch in list_chars:
    stoi[ch] = idx
    itos[idx] = ch
    idx += 1

stoi['.'] = 0
itos[0] = '.'

itos

In [33]:
block_size = 3
X = []
Y = []
for w in words[:3]:
    context = [0] * block_size
    print(w)
    for ch in w + '.':
        ix = stoi[ch]
        X.append(context)
        Y.append(ix)
        # print(''.join(itos[i] for i in context) + "--->" + ch)
        context = context[1:] + [ix]

X = torch.tensor(X)
Y = torch.tensor(Y)
YU = Y.unsqueeze(1)
Z = torch.cat((X, YU), dim=1)
Z


emma
olivia
ava


tensor([[ 0,  0,  0,  5],
        [ 0,  0,  5, 13],
        [ 0,  5, 13, 13],
        [ 5, 13, 13,  1],
        [13, 13,  1,  0],
        [ 0,  0,  0, 15],
        [ 0,  0, 15, 12],
        [ 0, 15, 12,  9],
        [15, 12,  9, 22],
        [12,  9, 22,  9],
        [ 9, 22,  9,  1],
        [22,  9,  1,  0],
        [ 0,  0,  0,  1],
        [ 0,  0,  1, 22],
        [ 0,  1, 22,  1],
        [ 1, 22,  1,  0]])

In [34]:
C = torch.randn(27, 2)
C

tensor([[-0.1242,  0.9962],
        [-1.6960,  1.3397],
        [-0.4327,  1.1031],
        [-0.0637,  1.0533],
        [ 1.4811,  0.9641],
        [ 0.6071, -1.5800],
        [ 0.6624, -0.5751],
        [-0.5692, -0.3483],
        [ 1.6457,  0.1535],
        [ 0.3901, -0.3112],
        [ 0.3183,  1.0439],
        [ 0.8733,  1.3807],
        [ 0.3417, -0.6011],
        [-0.0496,  0.0432],
        [-2.1254, -1.0947],
        [-0.4527,  0.0715],
        [ 0.7518,  1.3024],
        [ 1.3296,  0.6640],
        [ 0.6204, -1.3467],
        [-1.8907,  1.1998],
        [ 0.3066, -1.9276],
        [ 0.2097,  1.2540],
        [-0.3971, -0.7446],
        [-1.8534, -0.4474],
        [ 0.8431,  0.2776],
        [-1.2473,  1.8857],
        [-1.7470, -1.0682]])

In [36]:
C[X]

tensor([[[-0.1242,  0.9962],
         [-0.1242,  0.9962],
         [-0.1242,  0.9962]],

        [[-0.1242,  0.9962],
         [-0.1242,  0.9962],
         [ 0.6071, -1.5800]],

        [[-0.1242,  0.9962],
         [ 0.6071, -1.5800],
         [-0.0496,  0.0432]],

        [[ 0.6071, -1.5800],
         [-0.0496,  0.0432],
         [-0.0496,  0.0432]],

        [[-0.0496,  0.0432],
         [-0.0496,  0.0432],
         [-1.6960,  1.3397]],

        [[-0.1242,  0.9962],
         [-0.1242,  0.9962],
         [-0.1242,  0.9962]],

        [[-0.1242,  0.9962],
         [-0.1242,  0.9962],
         [-0.4527,  0.0715]],

        [[-0.1242,  0.9962],
         [-0.4527,  0.0715],
         [ 0.3417, -0.6011]],

        [[-0.4527,  0.0715],
         [ 0.3417, -0.6011],
         [ 0.3901, -0.3112]],

        [[ 0.3417, -0.6011],
         [ 0.3901, -0.3112],
         [-0.3971, -0.7446]],

        [[ 0.3901, -0.3112],
         [-0.3971, -0.7446],
         [ 0.3901, -0.3112]],

        [[-0.3971, -0

In [38]:
a = torch.arange(18)

In [40]:
a.view(9,2)

tensor([[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15],
        [16, 17]])