In [ ]:
import random

from imageio.v2 import sizes


def quicksort(arr):
    if len(arr) <= 1:
        return arr
    pivot = arr[len(arr) // 2]
    left = [x for x in arr if x < pivot]
    middle = [x for x in arr if x == pivot]
    right = [x for x in arr if x > pivot]

    return quicksort(left) + middle + quicksort(right)

num = list(range(1, 100))
random.shuffle(num)
print(num)
sorted_num = quicksort(num)
print(sorted_num)

In [5]:
sorted_num[-3]

97

In [2]:
import numpy as np

a = np.array([1,2,3,4,5])
a.shape

(5,)

In [8]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [9]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [17]:
a[1:3, :].shape

(2, 4)

In [13]:
a[1, :].shape

(4,)

In [14]:
a[1:2, :].shape

(1, 4)

In [18]:
a = np.array([[1,2], [3, 4], [5, 6]])

In [21]:
ix = np.array([[0, 1, 2], [0, 1, 0]])

print(a[ix])

[[[1 2]
  [3 4]
  [5 6]]

 [[1 2]
  [3 4]
  [1 2]]]


In [22]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

print(v.dot(w))
print(np.dot(v, w))

# Matrix / vector product; both produce the rank 1 array [29 67]
print(x.dot(v))
print(np.dot(x, v))

# Matrix / matrix product; both produce the rank 2 array
# [[19 22]
#  [43 50]]
print(x.dot(y))
print(np.dot(x, y))

219
219
[29 67]
[29 67]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [23]:
x = np.array([[1,2],[3,4]])

print(x.sum())

10


In [28]:
print(x.sum(axis=0))
print(x.sum(axis=1))

[4 6]
[3 7]


In [29]:
v = np.array([1,2,3])
w = np.array([4,5])
print(np.reshape(v, (3, 1)) * w)

[[ 4  5]
 [ 8 10]
 [12 15]]


In [30]:
x = np.array([[1,2,3], [4,5,6]])

In [31]:
v = np.array([1,2,3])
x + v

array([[2, 4, 6],
       [5, 7, 9]])

In [32]:
array = np.array([10, 3, 5, 1, 8, 6])
k = 3

# Get indices of k smallest elements (unordered)
k_min_indices = np.argpartition(array, k)[:k]

# If you want the actual smallest values (unordered)
print("Indices:", k_min_indices)
print("Values:", array[k_min_indices])

Indices: [3 2 1]
Values: [1 5 3]


In [11]:
x = np.random.randint(1, 11, size=(4, 1))
x

array([[4],
       [5],
       [6],
       [6]])

In [13]:
y = np.random.randint(1, 11, size=(4,))
y

array([ 8,  8,  3, 10])

In [14]:
x + y
(4,1)
(4,)

array([[12, 12,  7, 14],
       [13, 13,  8, 15],
       [14, 14,  9, 16],
       [14, 14,  9, 16]])