In [1]:
import torch


In [2]:
Y = [1, 4, 5, 6]

In [8]:
y = torch.tensor(Y)

In [9]:
y.shape

torch.Size([4])

In [19]:
g = y.unsqueeze(-1)

In [20]:
g.shape

torch.Size([4, 1])

In [28]:
g = torch.ones((3, 3))
g

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [34]:
h = g.unsqueeze(0)
m = h.unsqueeze(0)
m.shape

torch.Size([1, 1, 3, 3])

In [33]:
h

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])

In [60]:
a = torch.rand((3, 3))
a

tensor([[0.8998, 0.4499, 0.3800],
        [0.5525, 0.2836, 0.4083],
        [0.0952, 0.9291, 0.0907]])

In [76]:
X = torch.ones((2, 2), dtype=torch.int32)
X[0, 0] = 1; X[0, 1] = 2; X[1, 0] = 0; X[1, 1] = 1

In [72]:
a[torch.tensor([[1, 0], [0, 0]])].shape

torch.Size([2, 2, 3])

In [77]:
b = a[torch.tensor([2, 0])]
b

tensor([[0.0952, 0.9291, 0.0907],
        [0.8998, 0.4499, 0.3800]])

In [81]:
c = a[X]
c

tensor([[[0.5525, 0.2836, 0.4083],
         [0.0952, 0.9291, 0.0907]],

        [[0.8998, 0.4499, 0.3800],
         [0.5525, 0.2836, 0.4083]]])

In [86]:
t = torch.ones((2,3))
for i in [0,1]:
    for j in [0,1, 2]:
        t[i, j] = t[i, j] * (i + j)

t

tensor([[0., 1., 2.],
        [1., 2., 3.]])

In [90]:
t.sum(1, keepdim=True)

tensor([[3.],
        [6.]])