In [ ]:
import torch


In [ ]:
Y = [1, 4, 5, 6]

In [ ]:
y = torch.tensor(Y)

In [ ]:
y.shape

In [ ]:
g = y.unsqueeze(-1)

In [ ]:
g.shape

In [ ]:
g = torch.ones((3, 3))
g

In [ ]:
h = g.unsqueeze(0)
m = h.unsqueeze(0)
m.shape

In [ ]:
h

In [ ]:
a = torch.rand((3, 3))
a

In [ ]:
X = torch.ones((2, 2), dtype=torch.int32)
X[0, 0] = 1; X[0, 1] = 2; X[1, 0] = 0; X[1, 1] = 1

In [ ]:
a[torch.tensor([[1, 0], [0, 0]])].shape

In [ ]:
b = a[torch.tensor([2, 0])]
b

In [ ]:
c = a[X]
c

In [ ]:
t = torch.ones((2,3))
for i in [0,1]:
    for j in [0,1, 2]:
        t[i, j] = t[i, j] * (i + j)

t

In [ ]:
t.sum(1, keepdim=True)

In [ ]:
import numpy as np
import numpy.ma as ma

In [ ]:
a = np.array([3,2,1,2,-1])
b = ma.masked_array(a, mask=[0,0,1,0,0])

In [ ]:
c = np.ma.masked_array(a, mask=[1,0,1,0,0], fill_value=-18)

In [ ]:
a.shape

In [ ]:
a.reshape(-1, 1)

In [ ]:
a.reshape(1, -1)

In [12]:
import torch
batch_size, seq_len = 3, 5
A = torch.zeros((batch_size, seq_len))
A[0,0:] = 1
A[1,0:] = 2
A[2,0:] = 3

In [13]:
A

tensor([[1., 1., 1., 1., 1.],
        [2., 2., 2., 2., 2.],
        [3., 3., 3., 3., 3.]])

In [14]:
A1 = A.transpose(1,0)
A1

tensor([[1., 2., 3.],
        [1., 2., 3.],
        [1., 2., 3.],
        [1., 2., 3.],
        [1., 2., 3.]])

In [15]:
A2 = A.view(seq_len, -1)

In [16]:
A2

tensor([[1., 1., 1.],
        [1., 1., 2.],
        [2., 2., 2.],
        [2., 3., 3.],
        [3., 3., 3.]])

In [20]:
B = A.unsqueeze(1)
B

tensor([[[1., 1., 1., 1., 1.]],

        [[2., 2., 2., 2., 2.]],

        [[3., 3., 3., 3., 3.]]])

In [22]:
B = A[:, :3]

In [23]:
B

tensor([[1., 1., 1.],
        [2., 2., 2.],
        [3., 3., 3.]])

In [27]:
C = B.unsqueeze(1)
C.shape

torch.Size([3, 1, 3])

In [26]:
B

tensor([[1., 1., 1.],
        [2., 2., 2.],
        [3., 3., 3.]])